### PR TITLE
Upgrade from jbuilder to dune

### LINKED ISSUE #3: new release using dune
let's get rid of jbuilder!

### PR DESCRIPTION
**Pull request by shonfeder**
Closes #3 

I also added alcotest as a test dependency explicitly.

I haven't done any more involved testing than verifying that `dune runtest` works.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Thanks. Sorry for the late merge

**Comment by shonfeder** [comment]
Thank you! No worries :)

**Comment by kevinji** [comment]
@rgrinberg do you mind cutting a release for this change? dune-release depends on this package and it's a little unfortunate that it still depends on jbuilder 😄

**Comment by rgrinberg** [comment]
Submitted https://github.com/ocaml/opam-repository/pull/17149

**Pull request merged**
