### PR TITLE
4.08 update

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
This PR updates the minimum version to 4.08 (safe since the only public dependency of curly, `dune-release`, is already using 4.08 as minimum).

This has some advantages:

  * No need for the result package
  * No need for a shell wrapper, thus avoiding the headache of quoting arguments for the shell

There are some failing tests that have to be addressed though, but I'm putting the PR out there for discussion already.

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Added another fix for the argument order in the tests (where expected and actual were flipped) and fixed the issue where `-si` was parsed as `-s` when not using a shell.

**Comment by emillon** [comment]
Can you split just upgrading to 4.08+ (result etc) and the shell thing in different PRs?

**Comment by Leonidas-from-XIV** [comment]
@emillon Sure, I've removed the commits from here and created #17 (to be rebased when this is merged).

**Comment by emillon** [comment]
Thanks

**Pull request merged**
