### PR TITLE
Fix environment on Windows

### PR DESCRIPTION
**Pull request by emillon**
On Windows, an empty environment can cause curl to fail.

In particular, running curl seems to require `PATH` and `SYSTEMROOT`:

- if `PATH` is not set, the binary is not found
- if `SYSTEMROOT` is not set, address resolution fails at runtime

### CODE REVIEW

**Comment by emillon** [comment]
Ping @dra27 - do you know what would cause a cygwin binary started from a non-cygwin binary (everyone's favorite combination) to start correctly, but having no network access? I found that passing `PATH` and `SYSTEMROOT` fixes the issue but I'm not completely sure why this is working.

**Comment by dra27** [comment]
It's nothing to do with Cygwin...

```
C:\>set SYSTEMROOT=

C:\>C:\Windows\System32\curl.exe https://github.com
curl: (6) Could not resolve host: github.com

C:\>set SYSTEMROOT=C:\Windows

C:\>C:\Windows\System32\curl.exe -O https://github.com
curl: Remote file name has no length!
curl: try 'curl --help' for more information

C:\>C:\Windows\System32\curl.exe -LO https://github.com
curl: Remote file name has no length!
curl: try 'curl --help' for more information

C:\>C:\Windows\System32\curl.exe -o index.html https://github.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
```

**Comment by dra27** [comment]
I just quickly checked - `getaddrinfo` definitely fails if `SYSTEMROOT` isn't set. I haven't dug into precisely why, but it doesn't surprise me - it's probably trying to load `%SYSTEMROOT%\system32\drivers\etc\hosts`...

**Comment by emillon** [comment]
Ah! I was too quick to blame poor cygwin. I updated the description. Thanks!

**Comment by rgrinberg** [comment]
It seems strange that we are running the process with an empty environment in the first place. Can we just inherit the environment? I think that's what users would expect.

**Comment by dra27** [comment]
Depends on how thin a wrapper you're after - there are environment variables which can control curl which presently aren't exposed to it

**Comment by emillon** [comment]
Yes, including `*_PROXY`, `CURL_CA_BUNDLE`, `SSLKEYLOGFILE`... The curl process is shielded from these at the moment. Most of these can be passed as an argument so I think it's ok to clear them (but it's a design decision indeed).

**Comment by rgrinberg** [comment]
> Depends on how thin a wrapper you're after - there are environment variables which can control curl which presently aren't exposed to it

Would these environment variables control `libcurl` as well?

**Comment by dra27** [comment]
> > Depends on how thin a wrapper you're after - there are environment variables which can control curl which presently aren't exposed to it
> 
> Would these environment variables control `libcurl` as well?

Goodness, we're just scrubbing misbehaviour like that in opam's libs, but I really hope not!

**Comment by rgrinberg** [comment]
@emillon I gave you merge access to proceed as you see fit.

**Comment by emillon** [comment]
Thanks! I think that the most conservative option is to merge + release that PR does (this unlocks dune-release on windows for example) and keep the status quo for now.

> Would these environment variables control libcurl as well?

Some of them do: https://curl.se/libcurl/c/libcurl-env.html

**Comment by jonahbeckford** [comment]
Can someone merge this PR? It works on Windows. Thx

**Pull request merged**
